[api]
enabled = true
bind = ":8000"

[logging]
level = "info"
output = "stdout" 

#
[defaults]
max_connections = 0
client_idle_timeout = "0" 
backend_idle_timeout = "0"
backend_connection_timeout = "0"


[servers]


[servers.sample]
protocol = "tcp"
bind = "localhost:1880"
upstream = [
      "localhost:80",
  ]
max_connections = 8
#per_ip_connections = 5

[servers.sample.limit_reconnect_rate]
interval = "3s"
reconnects = 23333
